### ISSUE TITLE
Dash opens its own DB connections to Django

### ISSUE THREAD

**Issue by eddy-ojb** [GibbsConsulting/django-plotly-dash#18]
This is not necessarily an issue but I have noticed that Dash must be opening it's own session with the database.

I noticed this when I was accessing a database that had user specific security policies applied. In order to use a Django defined model, I had to send to the database the user id for Dash and Django separately to acquire data from the database. This makes sense considering that Dash is loaded in as an IFrame.

Are there plans on the roadmap to integrate the two more closely? Is this even practical in your opinion or will this need recoding by Plotly before this is possible?

**Comment by delsim** [comment]
To make sure I understand correctly: this is a setup where the Dash app talks to a database, and the Django process it is running inside is also talking to the same database. Further, the credentials used are different. Either (and probably both) of these facts means that there are multiple connections, in turn implying complexity and also presumably a lack of transaction integrity.

If so - no immediate integration plans, but that is because I've not thought about it much, so I'm not yet in a position to comment on how possible it is.

**Comment by eddy-ojb** [comment]
Hi delsim,

Yes you're interpretation is correct, although I don't know if it is strictly passing its own credentials - it could be  opening another connection with the same credentials. I don't know the exact method the database uses when it applies security policies to make transactions but I have to investigate this with our production team anyway so when I find out more I will update.

**Comment by GibbsConsulting** [comment]
Is this still a live issue, or can it be closed?

**Comment by eddy-ojb** [comment]
Closing. I think the problem was on the SQL Server side giving us a false impression.
