### ISSUE TITLE
Enable use in Django 3.0 and later

### ISSUE THREAD

**Issue by GibbsConsulting** [GibbsConsulting/django-plotly-dash#215]
Django 3.0 has been released, and contains some changes that are not yet compatible with `django-plotly-dash`.

For starters, `X-FRAME-OPTIONS` now prevents the serving of content into iframes by default. This is probably the cause of #214

**Comment by vladdoster** [comment]
I would love to take a wack at working on getting compatibility for django 3.0 correct. Do we think that is possible?

**Comment by GibbsConsulting** [comment]
The first step is to work out what has to be done, if anything, in addition to the iframe setting, to make dpd work with 3.0. From a quick scan of the 3.0 release notes this could turn out to be not very much!

Also there is a need to determine what could also be done to take advantage of the new 3.0 features; ASGI is notable here. However this wouldn't prevent using v3.0

**Comment by pallavg** [comment]
Hi - Just some feedback. I am using Django 3.0.2 and Plotly/Dash/Boostrap4. I am able to get django-plotly-dash working for a sample dashboard with the following:

1. In settings.py, set X_FRAME_OPTIONS = 'SAMEORIGIN'

2. In my html file, I had to use the plotly_app_bootrstrap tag for the app to render correctly.

```
{% extends "base.html" %}

{% load static %}

{% block page_content %}

{% load plotly_dash %}
<div class="{% plotly_class name='ProjectDashBoard' %} card">
{% plotly_app_bootstrap name='ProjectDashBoard' %}
</div>

{% endblock %}
```

If I use `plotly_app`, it shows it up inside a very small iframe. If I use `plotly_direct`, I just get a 'Loading...' output. I think this probably incorrect usage on my since I am using dash_boostrap_components + bootstrap4 css so plotly_app_bootstrap seems to be the way to go.

Beyond that, I didn't encounter any other major issues with using this nice library on Django 3.0.2.

It would be good if the X_FRAME_OPTIONS issue could be resolved in the near future.

**Comment by vladdoster** [comment]
@pallavg Thank you for this! Mind if I take your feedback and start a branch with the changes?

**Comment by pallavg** [comment]
@vladdoster Please go ahead. Thank you.

**Comment by vladdoster** [comment]
@GibbsConsulting I am unsure how to proceed. 

In Django 3.0, they changed the default `X_FRAME_OPTIONS` to `Deny` by default.

It seems that Django-Plotly needs `X_FRAME_OPTIONS = 'SAMEORIGIN'` to work properly. 

I am thinking this would need to be a documentation change to alert users as I am unaware of an option to do this programatically? Maybe add something to the middleware to do it under the hood?

**Comment by delsim** [comment]
Added use of X_FRAME_OPTIONS in PR #240

**Comment by robd003** [comment]
Hey guys, can we still support Django 2.2 since it's an LTS release?

**Comment by GibbsConsulting** [comment]
@robd003 until something requires us to move to v3.0 or beyond, we should continue to support it. For the moment, v1.2 (which requires Django < 3.0) is otherwise the same as the current latest release of 1.3.1 (which requires Django >= 3.0).

You'll have to use 1.2 until #246 gets resolved. At some point we may have new features that do actually require 3.n of Django; at that point we will endeavor to find some way of keeping 2.2 working whilst it is still supported.

**Comment by wtandrews** [comment]
I am not able to display a dash_table using v 1.4.2 of django_plotly_dash with django 3.0.9. I have tried suggestions above plus here:
https://docs.djangoproject.com/en/3.2/ref/clickjacking/
As well as disabling XFrameOptionsMiddleware. Nothing works. The debug console shows:

Refused to display '...' in a frame because it set 'X-Frame-Options' to 'deny'.

**Comment by GibbsConsulting** [comment]
@wtandrews Have you tried a more recent release? If that doesn't work, please open a new issue.
