### ISSUE TITLE
Exception 'Unable to find stateless DjangoApp called' or 'NoLayout'

### ISSUE THREAD

**Issue by miaoz2001** [GibbsConsulting/django-plotly-dash#283]
When i was working on some django-plotly-dash charts, i found a strange error happened from time to time,
I will see some error like
```
KeyError at /django_plotly_dash/app/DPD-xxx/
'Unable to find stateless DjangoApp called dpd-xxx'
```
Sometimes I got an error like
```
NoLayoutException at /reports/xxx/
Layout must be a dash component or a function that returns a dash component.
```

Sometime I just got an blank div with text error saying
```
Error loading layout
```

**BUT if i refresh the pages a few times then the errors just went away and the chart could be displayed correctly.**

Have anyone experienced this? Could anyone please help pointing out what i did it wrong?

Thanks!

**Comment by GibbsConsulting** [comment]
If it is intermittent then one cause could be some implicit or hidden state in your logic. Look for use of global variables and also any hidden assumptions about the order in which calls are invoked or the number of concurrent users of the application.

**Comment by miaoz2001** [comment]
I looked again one the doc of demo

> The registration code needs to be in a location
that will be imported into the Django process before any model or template tag attempts to use it. The example Django application
in the demo subdirectory achieves this through an import in the main `urls.py` file; any `views.py` would also be sufficient. 

I moved my app registration code in to urls, or views, then I see no more  error `Unable to find stateless DjangoApp called dpd-xxx`

---

But I still keep seeing the NoLayoutException error happened in the GET `.../django_plotly_dash/app/mydash/` . It likes that the layout (app.layout) is not available yet while the http call to get the content of mydash

I didn't put the app.layout = some_layout() right after the app = DjangoDash() like it is in the demo, is that a problem?

I put app.layout =some_layout() in a django template view which might be delayed or slow to load. Could that a problem?

I am curious when do the GET `.../django_plotly_dash/app/mydash/` fired out?

Thanks!

**Comment by GibbsConsulting** [comment]
Your issue sounds like your code does not populate the app.layout variable for every call. Try putting it somewhere that is always loaded, not only invoked when a particular view is called.

DPD calls multiple views - your template will insert an iframe that makes a separate call for the initial layout - this will not necessarily invoke the same code as your template view. Later calls, such as when updating the Dash application due to user input, also will not involve your template view.

**Comment by miaoz2001** [comment]
Thanks! I got it, I should just put all the app, layout, callback in one file and imported all at once, to keep it simple, instead i was trying to put them into a class view, which caused strange errors.

Now it is working anyway
However i knid of hope that the app, layout and callback could be enclosed inside of a class view but haven't figure it out yet

Thanks!

**Comment by GibbsConsulting** [comment]
@miaoz2001 good to hear that the error is cleared up. However, what is your motivation behind trying to encapsulate the app within a class view? The app is something that gets used by the template rendered as a result of the response of your view, rather than from within your view.

If you're looking to control the content of the app based on your view, then take a look at [initial_arguments](https://django-plotly-dash.readthedocs.io/en/latest/template_tags.html#the-plotly-app-template-tag) to the template tags - this allows you to instantiate an instance of an app with values from your view.
