### ISSUE TITLE
Make codebase compatible with Dash 2.0 release

### ISSUE THREAD

**Issue by GibbsConsulting** [GibbsConsulting/django-plotly-dash#354]
As well as #351, there is also a need to make `django-plotly-dash` work with the recent v2.x release(s) of Dash.
One issue has already been reported as #353

**Comment by limsammy** [comment]
@GibbsConsulting @IDepla Hey guys, running into this issue currently.

What is your advice on the best way to implement this fix? I am currently going to simply fork dash, add the fix, and use that for the project until there is an official patch for overriding the dash func in django-plotly-dash, and we can revert back to the official Dash package...

I'm not sure how viable this is, or if I can simply override it myself within the django app without having to touch either dash or django-plotly-dash. 

How did you implement this fix? @IDepla I know it is a very ill advised practice to edit anything installed directly under ./myenv/site_packages/, so I am leaning towards forking, adding your fix, and installing with `pip install -e git+https://github.com/myorg/dash-fork.git`

Any thoughts on this strategy?

**Comment by limsammy** [comment]
Any update on this?

**Comment by GibbsConsulting** [comment]
@limsammy one alternative could be to monkey patch that function at runtime - in other words, import the module it is in and set the function equal to the new desired one. You will have to ensure that you do this patching prior to executing any callback.

**Comment by IDepla** [comment]
@limsammy it was meant to be temporary until dash fixes the problem. 

I was wondering (but I didn't try), a way to operationalize @GibbsConsulting's comment could be to hijack directly the module cache (https://docs.python.org/3/reference/import.html) since the load of the Django settings. Either way, the dash app is imported after the settings, so you override the cache reference before is called by any other module.  

If the fix has to live for longer than expected, a better way would be to just add the variables that you need (and are validated) instead of copying all the **kwargs.

**Comment by KuechlerO** [comment]
Another new feature that came in with Dash 2.0 is the "flexible callback".
However, this fails currently when using `django-plotly-dash`.

Take a look here:
[Flexible callbacks failing validation](https://github.com/plotly/dash/issues/1881)

**Comment by GibbsConsulting** [comment]
v2.0.0 is now out!
