### ISSUE TITLE
cannot run from inside conda a venv

### ISSUE THREAD

**Issue by wave-DmP** [GibbsConsulting/django-plotly-dash#44]
Hi,

Can you please post a tutorial to set up the demo in an anaconda virtual env (noob question, but nonetheless it would be helpful).

**Comment by delsim** [comment]
Adding a tutorial sounds like a good idea. Are you seeing some sort of error at the moment?

I've just tried the following steps (on a linux machine):

First, get a conda install and make an environment.

Then, in that environment:

`conda install Django Flask redis pandas`

`pip install channels channels-redis daphne daphne-redis django-bootstrap4 dash dash-core-components dash-html-components dash-renderer plotly dpd-components`

`python setup.py develop`

The last of those needs to be run in the root directory of the source tree.

If I then run the ``prepare_demo.sh`` script (having already run the ``prepare_redis.sh`` one or equivalent) I get a fully functional demo.

**Comment by eddy-ojb** [comment]
If anyone is having issues for Anaconda on **Windows**, the instructions for newbies to run the demo are slightly different. 

**Step 1:** For now, you can go to this [dev branch](https://github.com/eddy-ojb/django-plotly-dash/tree/conda_env_req) and download the `requirements.yaml` and `dev_requirements.yaml` file.

**Step 2:** In order to setup a minimally required environment to run django-plotly-dash, open up a command prompt / Anaconda Prompt and run the following in the same directory as the .yaml files:

`conda env create --name dpd-demo --file requirements.yaml
`
, replacing `dpd-demo` with the desired name for your environment.

**Step 3:** Obviously, you want to run the demos so after this run:

conda env update --name dpd-demo --file dev_requirements.yaml

, replacing dpd-demo with your environment name.

**Step 4:** At this point, if you are on Linux, my guess is that you can follow the original instructions to run the .sh files to setup redis and django. If on Windows, you need to do the following:

 [Download the .msi for Redis](https://github.com/MicrosoftArchive/redis/releases), an in memory data structure store. Run it, keeping all default settings.

**Step 5:** Assuming you have downloaded the django-plotly-dash repository, navigate to the root directory and install it, first making sure your env is activated:

```
activate dpd-demo
python setup.py develop
```

**Step 6:** Run the following commands, navigating to the demo directory in the process:

`cd demo`
`python manage.py migrate`
`python manage.py collectstatic -i "*.py" -i "*.pyc" --noinput --link`
`python manage.py runserver`

Navigating to `http://127.0.0.1:8000/` should display the demos. If any demos do not work, it is probably the static references. My temporary resolution for this is to get the `demo/static` folder and copy and paste to `demo/demo/static`, replacing the files already there.

**Comment by GibbsConsulting** [comment]
Just merged PR #45 (thanks to @eddy-ojb!) which adds in the needed conda yaml files.

**Comment by GibbsConsulting** [comment]
Assuming this issue is now resolved
