### ISSUE TITLE
Having issues with dynamically loading images in dash app.  Demo-nine missing

### ISSUE THREAD

**Issue by giaxle** [GibbsConsulting/django-plotly-dash#464]
Trying to port existing dash apps into dpd. I'm having an issue with displaying images or other media in my django dash app. The documentation doesn't say much on the matter. The dash app requests are return 404 not found errors even though the files are in the assets folders. Have also tried with static folders.  I also noticed that demo-nine's images are coming up as broken links and demo-nine is commented out from the live demo. My use case is for the user to upload and view files through the dash app. Is this supported or am I using django-plotly-dash for the wrong use case.

**Comment by delsim** [comment]
@giaxle I think you'll have to provide some more details before it is possible to comment further.

One first step might be to pull the git repo and follow the steps to get the demo running; this would make sure that it is possible for things to work correctly on your machine. Once that is working, then adding dpd to your project and validating that a simple app is working could be a next step. Then, adding in your existing dash app should fail but the resultant error messages would be due to any specific issue that you are facing.

It is certainly true that setting up static assets is one of the more involved steps in using dpd, and also that it is not that well documented. Partly this is due to the very different way that dash handles static assets compared to Django. However, using them is most definitely possible.

**Comment by giaxle** [comment]
I ended up figuring it out. I was confused on where to put the static files folder in the hierarchy of the app. It was just in the wrong place.
