### ISSUE TITLE
Django 2.0+ Only?

### ISSUE THREAD

**Issue by hannylicious** [GibbsConsulting/django-plotly-dash#9]
Just FYI - you might want to mention or put somewhere that this is Django2.0+ only (because of how the URL's are structured).

**Comment by GibbsConsulting** [comment]
Thanks for the observation. I've tried moving to the older url function for path registration, but that turns out to be a bit of a pain due to the way Dash registers its various endpoints.
The efforts can be found at [https://github.com/delsim/django-plotly-dash/commits/django_version](https://github.com/delsim/django-plotly-dash/commits/django_version).

**Comment by GibbsConsulting** [comment]
Dcoumentation and setup files updated as part of 0.4.3 prerelease changes.
